apiVersion: v1
kind: ConfigMap
metadata:
  name: go-cart-config
  labels:
    app: go-cart
    app.kubernetes.io/name: go-cart
    app.kubernetes.io/part-of: go-cart
data:
  config.yml: |
    gocart:
      cache_path: /opt/app-root/tmp
      server:
        host: 0.0.0.0
        base_path: "/go-cart"
        port: 8080
        timeout:
          server: 30
          read: 15
          write: 10
          idle: 5