---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-cart
  labels:
    app: go-cart
    app.kubernetes.io/name: go-cart
    app.kubernetes.io/part-of: go-cart
spec:
  selector:
    matchLabels:
      app: go-cart
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: go-cart # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: go-cart
          imagePullPolicy: Always
          image: quay.io/PolyglotSystems/go-cart:latest
          livenessProbe:
            httpGet:
              path: /healthz
              port: api
            initialDelaySeconds: 5
            periodSeconds: 30
          startupProbe:
            httpGet:
              path: /healthz
              port: api
            initialDelaySeconds: 5
            failureThreshold: 30
            periodSeconds: 5
          ports:
            - containerPort: 8080
              name: api
          volumeMounts:
            - name: go-cart-config
              mountPath: "/opt/app-root/config.yml"
              readOnly: true
      volumes:
        # You set volumes at the Pod level, then mount them into containers inside that Pod
        - name: go-cart-config
          configMap:
            # Provide the name of the ConfigMap you want to mount.
            name: go-cart-config
            # An array of keys from the ConfigMap to create as files
            items:
              - key: "config.yml"
                path: "config.yml"
            defaultMode: 0644